### ISSUE TITLE
SongHashData does not exist

### ISSUE THREAD

**Issue by jmrtsh** [HuJohner/beatsaber-custom-level-score-fix#1]
For me the folder which saves Beat Saber data does not contain a SongHashData.dat file

**Comment by HuJohner** [comment]
Could you provide me with some more information like OS, Steam/Oculus, HDM?

**Comment by jmrtsh** [comment]
Hi, of course, Steam on Windows 10 with a Windows mixed reality headset, a Samsung Odyssey+ HMD to be exact. After playing a bit the file interestingly just appeared, but without all of my now lost data. Thanks for trying to help tough :)

**Comment by HuJohner** [comment]
Hm, that is odd... Unfortunately, I can't help unless the SongHashData is populated. However, you might be in luck as for me it recently switched back around, so maybe your scores could be back?

**Comment by jmrtsh** [comment]
Sorry I completely lost track of this: I actually managed to get parts of my scores back with old backups and your fix, so thank you very much, even though I don't exactly know what the issue with the missing file was I think I can close this :D
